In [2]:
import numpy as np
print(np.__version__)

1.18.2


In [5]:
l1 = [0,1,2,3,4,5,6,7,8,9]
One_Dim_arr = np.array(l1)
print(One_Dim_arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
boolean_array = np.full((3,3),True,dtype=bool)
print(boolean_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [19]:
boolean_array = np.ones((3,3),dtype=bool)
print(boolean_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [28]:
arr = np.arange(10,30,2) #Extract even number 
print(arr)

[10 12 14 16 18 20 22 24 26 28]


In [29]:
num = int(input("Enter a number: "))
if (num % 2) == 0:
   print("{0} is Even".format(num))
else:
   print("{0} is Odd".format(num))

Enter a number: 5
5 is Odd


In [41]:
arr = np.array([range(30)])
arr[arr % 2 == 0]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [43]:
arr[arr % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [47]:
arr = np.array([range(30)])
arr[arr % 2 == 0] = -2  # change even number by -2
print(arr)

[[-2  1 -2  3 -2  5 -2  7 -2  9 -2 11 -2 13 -2 15 -2 17 -2 19 -2 21 -2 23
  -2 25 -2 27 -2 29]]


In [48]:
arr = np.array([range(30)])
arr[arr % 2 == 1] = -2  # change odd number by -2
print(arr)

[[ 0 -2  2 -2  4 -2  6 -2  8 -2 10 -2 12 -2 14 -2 16 -2 18 -2 20 -2 22 -2
  24 -2 26 -2 28 -2]]


In [55]:
arr = np.arange(10)
out_put = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out_put)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [56]:
arr = np.arange(10)
reshape_arr = arr.reshape(2,5)
print(reshape_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [65]:
arr1 = np.arange(10).reshape(2,5)
print("arr1",arr1)
arr2 = np.arange(10,20).reshape(2,5)
print("arr2",arr2)

np.concatenate([arr1,arr2],axis=0)

arr1 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr2 [[10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
np.vstack([arr1,arr2])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
np.hstack([arr1,arr2])

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [70]:
np.r_[np.repeat(arr,3),np.tile(arr,3)]

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [72]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [73]:
np.where(a==b)

(array([1, 3, 5, 7]),)

In [74]:
a = np.array([10,6,7,8,3,4,3,4,5,6])
index = np.where((a>=5) & (a<=10))
a[index]

array([10,  6,  7,  8,  5,  6])

In [76]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([10,  6,  7,  8,  5,  6])

In [78]:
a[(a>=5) & (a<=10)]

array([10,  6,  7,  8,  5,  6])

In [81]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[1,2,0]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [85]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[2,0,1],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [86]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [87]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [89]:
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.randint(low = 5, high = 10, size = (5,3)) + np.random.random((5,3))
print(rand_arr)

[[7.42403931 8.03878398 5.82368322]
 [9.36316953 5.02935527 8.01250636]
 [7.58100391 9.97488712 6.2900914 ]
 [7.43823414 6.85989284 8.58715801]
 [8.35032551 7.94346207 7.76539966]]


In [91]:
rand_arr = np.random.uniform(5,10,size=(5,3))
print(rand_arr)

[[5.75338655 6.81522779 6.08664975]
 [8.41742727 7.92608643 9.2533526 ]
 [6.7426373  5.64574013 5.64142517]
 [5.88913518 8.19913143 9.9510142 ]
 [6.16669172 8.35714897 7.60479025]]


In [97]:
arr = np.arange(9)
mean = np.mean(arr)
print(mean)

4.0


In [108]:
arr = np.arange(9,16)
mediam = np.median(arr)
print(medium)

12.0


In [115]:
from scipy import stats
l3 = [3,4,5,2,3,3,4,2,34]
arr = np.array(l3)
mode = stats.mode(l3)
print(mode)
mode = stats.mode(arr)
print(mode)

ModeResult(mode=array([3]), count=array([3]))
ModeResult(mode=array([3]), count=array([3]))


In [117]:
from sklearn import preprocessing
import numpy as np

a = np.random.random((1, 4))
a = a*20
print("Data = ", a)

# normalize the data attributes
normalized = preprocessing.normalize(a)
print("Normalized Data = ", normalized)

Data =  [[13.49573385  4.06734646  6.26806504  6.23370477]]
Normalized Data =  [[0.81113507 0.24446002 0.37672997 0.37466481]]


In [123]:
def softmax(x):
    print("""Compute softmax values for each sets of scores in x.""")
    return np.exp(x) / np.sum(np.exp(x), axis=0)
arr = np.arange(10)
print(softmax(arr))

Compute softmax values for each sets of scores in x.
[7.80134161e-05 2.12062451e-04 5.76445508e-04 1.56694135e-03
 4.25938820e-03 1.15782175e-02 3.14728583e-02 8.55520989e-02
 2.32554716e-01 6.32149258e-01]


In [125]:
arr.dtype

dtype('int64')

In [126]:
arr.shape

(10,)

In [128]:
arr3 = np.zeros((3,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [130]:
arr5 = np.empty((2,3))
print(arr5)

[[4.67880393e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [132]:
a = arr.min()
print(a)

0


In [134]:
a = arr.max()
print(a)

9


In [136]:
a = arr.sum()
print(a)

45


In [137]:
a = np.sqrt(arr)
print(a)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [139]:
a = np.square(arr)
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [142]:
add2array = np.add(arr,arr)
print(add2array)

[ 0  2  4  6  8 10 12 14 16 18]


In [143]:
a = np.arange(30).reshape(3,10)
print(a)
a.resize((2,15))
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
